#!/usr/bin/env bash
#platanos
for (( n=1; i < 100; i++ ))
do
    if (( n % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( n % 3 == 0 )); then
	echo "Fizz"
    elif (( n % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$n"
    fi
    (( n+=1 ))
done
