#!/usr/bin/env bash
#comentairo banana
p="/etc/passwd"
while IFS=: read  -r u g h c U P US
do
	echo The user "$u" is part of the "$g" gang, lives in "$h" and rides "$c". "$U" place is protected by the passcode "$P", more info about the user here: "$US"
done < "$p"
