#!/usr/bin/env bash
#hola
{
sudo touch /var/run/myscript.pid
}
echo $$ >> /var/run/myscript.pid
while true ; do
	trap "echo I hate the kill command" 15
	trap "echo Y U no love me?!" 9
	echo To infinity and beyond
	sleep 2
	trap "sudo rm /var/run/myscript.pid"
done

