#!/usr/bin/env bash
#hola
sudo bash -c echo $$ > /var/run/myscript.pid
while ((1)) true 
do
	 echo To infinity and beyond
	         sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM 
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done

