#!/usr/bin/env bash
#hola
p=/var/run/my_process.pid 
if [ "${1}" == "star"]
then
	./manage_my_process &
echo "$$" >>$p
echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	 kill $(cat "$p") & rm -f "$p"
	echo "manage_my_process stopped"
elif [ "${1}" == "restart" ]
then
	kill $(cat "$p") & rm -f "p"
	./manage_my_process &
	echo "$!" > $p
	echo "manage_my_process restarted"
else
	Usage: manage_my_process {start|stop|restart}
fi
