#!/usr/bin/env bash
#no
echo $$ >> /var/run/myscript.pid

trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U love me ?!; exit" SIGINT

while true;
do
 echo To infinity and beyond 
sleep 2
 trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT || SIGTERM
done
